compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  gradient_accumulation_steps: 4
  gradient_clipping: 1.0
  zero_stage: 3
  zero3_init_flag: true
  offload_optimizer_device: none
  offload_param_device: none
  communication_data_type: bf16
  dist_backend: nccl
  dist_inference: false
  dump_state: false
  elastic_checkpoint: false
  bf16:
    enabled: true
  fp16:
    enabled: false
  wall_clock_breakdown: false
  steps_per_print: 2000
  train_batch_size: 8
  train_micro_batch_size_per_gpu: 1
  gradient_accumulation_steps: 4
distributed_type: DEEPSPEED
downcast_bf16: 'no'
enable_cpu_affinity: false
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
